[font]
size = 14.0

[window]
dynamic_padding = true
opacity = 0.95
decorations = "buttonless"

[scrolling]
history = 15000

[keyboard]
bindings = [
    { key = "i", mods="Command", chars = "\u0002"}  # fix tmux binding for mac
]

[mouse]
hide_when_typing = true



# # Default colors
# [colors.primary]
# background = '#282828'
# foreground = '#eeeeee'
#
# # Normal colors
# [colors.normal]
# black   = '#282828'
# red     = '#f43753'
# green   = '#c9d05c'
# yellow  = '#ffc24b'
# blue    = '#b3deef'
# magenta = '#d3b987'
# cyan    = '#73cef4'
# white   = '#eeeeee'
#
# # Bright colors
# [colors.bright]
# black   = '#4c4c4c'
# red     = '#f43753'
# green   = '#c9d05c'
# yellow  = '#ffc24b'
# blue    = '#b3deef'
# magenta = '#d3b987'
# cyan    = '#73cef4'
# white   = '#feffff'

# [colors.primary]
# background = '#191724'
# foreground = '#e0def4'
#
# [colors.cursor]
# text = '#e0def4'
# cursor = '#524f67'
#
# [colors.vi_mode_cursor]
# text = '#e0def4'
# cursor = '#524f67'
#
# [colors.selection]
# text = '#e0def4'
# background = '#403d52'
#
# [colors.normal]
# black = '#26233a'
# red = '#eb6f92'
# green = '#31748f'
# yellow = '#f6c177'
# blue = '#9ccfd8'
# magenta = '#c4a7e7'
# cyan = '#ebbcba'
# white = '#e0def4'
#
# [colors.bright]
# black = '#6e6a86'
# red = '#eb6f92'
# green = '#31748f'
# yellow = '#f6c177'
# blue = '#9ccfd8'
# magenta = '#c4a7e7'
# cyan = '#ebbcba'
# white = '#e0def4'

[colors.hints]
start = {foreground = '#908caa', background = '#1f1d2e' }
end = { foreground = '#6e6a86', background = '#1f1d2e' }


[colors.primary]
background = '#0E1415'
foreground = '#CECECE'

[colors.cursor]
text = '#0E1415'
cursor = '#CECECE'

[colors.normal]
black = '#0E1415'
red = '#e25d56'
green = '#73ca50'
yellow = '#e9bf57'
blue = '#4a88e4'
magenta = '#915caf'
cyan = '#23acdd'
white = '#f0f0f0'

[colors.bright]
black = '#777777'
red = '#f36868'
green = '#88db3f'
yellow = '#f0bf7a'
blue = '#6f8fdb'
magenta = '#e987e9'
cyan = '#4ac9e2'
white = '#FFFFFF'

